### ISSUE TITLE
Cross-Server

### ISSUE THREAD

**Issue by XZot1K** [XZot1K/HyperDrive#16]
**The feature in general is being reworked. I simply do not like the way it works currently and is not very user friendly.**

**TODO**
- [ ] Write foundation for the entire feature to utilize the BungeeCord Messaging Channel (Currently uses MySQL).
- [ ] The feature should be usable under SQLite and MySQL (Currently only MySQL).
- [ ] Implement Cross-Server features into the teleportation commands.
- [ ] Merge a BungeeCord version into the base plugin to handle middle-man actions.
